#!/usr/bin/env bash
# Write Sources/sod/Version.swift from the current git tag (or $SOD_VERSION).
# Run before any build. The file is git-ignored and regenerated, so regenerating it
# never dirties the tree. A plain script (not a SwiftPM plugin) so it can call git.
set -euo pipefail
cd "$(dirname "$0")/.."
OUT="Sources/sod/Version.swift"

if [ -n "${SOD_VERSION:-}" ]; then
  V="$SOD_VERSION"                                  # Homebrew / release override
elif git rev-parse --git-dir >/dev/null 2>&1; then
  V="$(git describe --tags --dirty 2>/dev/null || echo 0.1.0-dev)"
else
  V="0.1.0-dev"                                     # source tarball, no .git
fi
V="${V#v}"                                          # strip leading v from tags (v0.1.0 -> 0.1.0)

NEW="// GENERATED by scripts/gen-version.sh — do not edit, do not commit.
enum Build { static let version = \"${V}\" }
"
# Only rewrite if changed (keeps incremental builds warm).
if [ -f "$OUT" ] && [ "$(cat "$OUT")" = "$NEW" ]; then exit 0; fi
printf '%s' "$NEW" > "$OUT"
echo "gen-version: $OUT -> $V"
